name: Deploy to AWS
on:
 push:
   branches:
   - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
   runs-on: ubuntu-latest

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-arn: github_actions_role #${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    # terraform apply -auto-approve
    # - name: Configure AWS Credentials for China region audience
      # uses: aws-actions/configure-aws-credentials@v5.0.0
      # with:
        # audience: sts.amazonaws.com.cn
        # aws-region: cn-northwest-1
        # role-to-assume: arn:aws-cn:iam::123456789100:role/my-github-actions-role
    - name: Run Terraform
      run: |
        terraform init
