name: Reusable Terraform Workflow

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      region:
        required: true
        type: string
      deploy:
        required: true
        type: boolean
    secrets:
      tf_token:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
         
      - name: Terraform Init
        run: terraform init -backend-config="key=${{ inputs.app_name }}-${{ inputs.environment }}.tfstate"
      - name: Terraform Plan
        run: terraform plan -out=plan.tfout
      - name: Terraform Apply (if deploy)
        if: inputs.deploy
        run: terraform apply plan.tfout