name: Terraform CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -out=plan.tfout
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: plan.tfout

  apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: plan  # Optional if separating workflows
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply plan.tfout